version: '3.4'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  trabfaculdadebackend:
    image: trabfaculdadebackend
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 4000:4000
volumes:
  postgres-data:
networks:
  default:
    name: local-network
    external: true